[project]
name = "llm-for-css"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=1.2.0",
    "openai>=1.78.1",
    "python-dotenv>=1.2.3",
    "tqdm>=4.67.1",
]

[dependency-groups]
docs = [
    "mkdocs-jupyter>=0.26.3",
    "mkdocs-material>=9.7.7",
]
